# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55ba4a5a426bc0e2cd5b4be20a3b44702d2bc8973ab09591369d9bcb3ec87511f43e2e1c0ee83fb09739a0c24d0ede9235caab3f2b73e8012222d4004653793

test:
  secret_key_base: d15ec888a730d193d558619a74039e6237e0762e21e787837a55ae4021118e53d7521a873ba3833b7a8279e974b9f4f3ebf4af9000596d50db3dd937dd80523c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
